name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-python@v1
        with:
          python-version: "3.10.2"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run unit tests
      #  run: |
      #    python test_application.py
